spring:
  datasource:
    url: jdbc:h2:file:~/letters/db
    username: human
    password: qwerty
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always

